### ISSUE TITLE
Not working with lit-html directives

### ISSUE THREAD

**Issue by kuka-radovan** [cfware/babel-plugin-template-html-minifier#6] opened 2018-11-14 15:58 UTC
This plugin doesn't work with lit-html build-in [directives](https://lit-html.polymer-project.org/guide/template-reference#built-in-directives).

## example:
```
html`
  ${when(checked,
    () => html`Checkmark is checked`, 
    () => html`Checkmark is not checked`
  )}
`
```

It throws following error:
```
Error: html-minifier deleted something major, cannot proceed.
    at minify (/babel-plugin-template-html-minifier/index.js:74:10)
    at PluginPass.TaggedTemplateExpression (/babel-plugin-template-html-minifier/index.js:163:6)
    at newFn (/@babel/traverse/lib/visitors.js:193:21)
    at NodePath._call (/@babel/traverse/lib/path/context.js:53:20)
    at NodePath.call (/@babel/traverse/lib/path/context.js:40:17)
    at NodePath.visit (/@babel/traverse/lib/path/context.js:88:12)
    at TraversalContext.visitQueue (/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitSingle (/@babel/traverse/lib/context.js:90:19)
    at TraversalContext.visit (/@babel/traverse/lib/context.js:146:19)
    at Function.traverse.node (/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/@babel/traverse/lib/path/context.js:95:18)
    at TraversalContext.visitQueue (/@babel/traverse/lib/context.js:118:16)
    at TraversalContext.visitMultiple (/@babel/traverse/lib/context.js:85:17)
    at TraversalContext.visit (/@babel/traverse/lib/context.js:144:19)
    at Function.traverse.node (/@babel/traverse/lib/index.js:94:17)
    at NodePath.visit (/@babel/traverse/lib/path/context.js:95:18)
    at compiler.run (/Users/kuko/Workspace/Orange/dev-tools/lit-scripts/scripts/build.js:41:23)
    at finalCallback (/webpack/lib/Compiler.js:210:39)
    at hooks.done.callAsync.err (/webpack/lib/Compiler.js:226:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tapable/lib/Hook.js:154:20)
    at onCompiled (/webpack/lib/Compiler.js:224:21)
    at hooks.afterCompile.callAsync.err (/webpack/lib/Compiler.js:552:14)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tapable/lib/Hook.js:154:20)
    at compilation.seal.err (/webpack/lib/Compiler.js:549:30)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tapable/lib/Hook.js:154:20)
    at hooks.optimizeAssets.callAsync.err (/webpack/lib/Compilation.js:1312:35)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:6:1)
    at AsyncSeriesHook.lazyCompileHook (/tapable/lib/Hook.js:154:20)
    at hooks.optimizeChunkAssets.callAsync.err (/webpack/lib/Compilation.js:1303:32)
```

**Comment by coreyfarrell** [comment] 2018-11-14 16:00
Please provide a specific example code.

**Comment by kuka-radovan** [comment] 2018-11-14 16:10
Sry, I submitted insufficient description by mistake.

**Comment by coreyfarrell** [comment] 2018-11-14 16:36
I just tested this without issue.  Please share the options you are passing to this babel plugin.

**Comment by kuka-radovan** [comment] 2018-11-14 16:53
this is my babel configuration inside webpack config

```
{
  test: /\.(js|mjs)$/,
  include: paths.appSrc,
  loader: 'babel-loader',
  options: {
    babelrc: false,
    configFile: false,
    presets: [
      ['@babel/preset-env', {
        modules: false,
        ignoreBrowserslistConfig: true,
        targets: {
          esmodules: true, 
        }
      }]
    ],
    plugins: [
      ['@babel/plugin-proposal-decorators',{ 'legacy': true }],
      ['@babel/plugin-proposal-class-properties', { 'loose': true }]
      ['template-html-minifier', {
        modules: {
          'lit-html': ['html'],
          '@polymer/lit-element': ['html'],
        },
        htmlMinifier: {
          collapseWhitespace: true
        }
      }]
    ],
    cacheDirectory: true,
    cacheCompression: true,
    compact: true
  }
}
```

**Comment by coreyfarrell** [comment] 2018-11-14 17:05
Sorry I'm still unable to reproduce this issue with the information you've given.  At this point I think I need a link to a demo repository - preferably the minimum needed to demonstrate the problem you are having.

**Comment by kuka-radovan** [comment] 2018-11-14 17:22
Ok, I will send it later today or tomorrow.

**Comment by coreyfarrell** [comment] 2018-11-24 11:58
@kuka-radovan Ping... I cannot help without the requested bug demo.

**Comment by kuka-radovan** [comment] 2018-11-24 20:31
I am sorry, I had some health problems. I will look at it next week. I appreciate your interest.

**Comment by coreyfarrell** [comment] 2018-11-25 06:30
I hope you feel better soon.  I will await your response next week.

**Comment by kuka-radovan** [comment] 2018-12-04 08:40
I am sorry... I have a lot of work this days. But I will definitely get back to this issue as soon as possible.

**Comment by coreyfarrell** [comment] 2018-12-14 14:17
For now I'm going to close this ticket as I'm unable to reproduce.  Please feel free to reopen if you can provide a demo repository so I have something to investigate.

**Closed as completed by coreyfarrell** 2018-12-14 14:17 UTC
